### ISSUE TITLE
related work: mbox

### ISSUE THREAD

**Issue by Mic92** [Ekleog/toboggan#1]
There is a similar project that was created presented in a paper and does something similar compared to your project: https://people.csail.mit.edu/nickolai/papers/kim-mbox.pdf

Just so you know.

**Comment by Mic92** [comment]
There is nothing actionable in this issue. This was just a general information.

**Comment by Ekleog** [comment]
Thank you for the information! I have added a mention in the readme, given this is abandonware-ish, due to shifting priorities.
